### ISSUE TITLE
PhoneGap error

### ISSUE THREAD

**Issue by dinami-k** [darryncampbell/DataWedge-Cordova-Sample#4]
Hi, compile with phonegap

**LogError**

Build Date: 2018-09-18 12:22:32 +0000
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Fetching plugin "cordova-plugin-whitelist@1" via npm
Installing "cordova-plugin-whitelist" at "1.3.3" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.

Fetching plugin "com-darryncampbell-cordova-plugin-intent@^1.0.0" via npm
Installing "com-darryncampbell-cordova-plugin-intent" at "1.1.1" for android
Subproject Path: CordovaLib
--------------------------------------------------------------------------------
PROJECT PROPERTIES
--------------------------------------------------------------------------------
# This file is automatically generated by Android Tools.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
# This file must be checked in Version Control Systems.
#
# To customize properties used by the Ant build system edit
# "ant.properties", and override values to adapt the script to your
# project structure.
#
# To enable ProGuard to shrink and obfuscate your code, uncomment this (available properties: sdk.dir, user.home):
#proguard.config=${sdk.dir}/tools/proguard/proguard-android.txt:proguard-project.txt
# Project target.
target=android-25
android.library.reference.1=CordovaLib
cordova.system.library.1=com.android.support:support-v4:27.1.0
--------------------------------------------------------------------------------
COMPILE OUTPUT
--------------------------------------------------------------------------------
Subproject Path: CordovaLib
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
	at build_300e2wpe4ho3g9dxhdxnd75cv.run(/project/build.gradle:137)
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
Incremental java compilation is an incubating feature.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
The ProjectDependency.getProjectConfiguration() method has been deprecated and is scheduled to be removed in Gradle 4.0.
ModuleDependency.getConfiguration() has been deprecated and is scheduled to be removed in Gradle 4.0. Use ModuleDependency.getTargetConfiguration() instead.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'project'.
> Could not resolve all dependencies for configuration ':_debugApkCopy'.
   > Could not find com.android.support:support-v4:27.1.0.
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.307 secs
Error: /project/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'project'.
> Could not resolve all dependencies for configuration ':_debugApkCopy'.
   > Could not find com.android.support:support-v4:27.1.0.
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by darryncampbell** [comment]
Looks like it is related to https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent/issues/59.  Can you please try updating to the latest version of the Android platform (https://cordova.apache.org/announcements/2018/02/26/cordova-android-7.1.0.html)

**Comment by dinami-k** [comment]
Hi darryn. Thanks a lot.... I saw the link yesterday, but my error is when i compile with phonegap build 

[phonegap build](https://build.phonegap.com)

I have a problem with
com-darryncampbell-enterprisebarcode 
and
com-darryncampbell-cordova-plugin-intent

few months a go  I was able to compile inside phonegap build

can you help me please?

**Comment by darryncampbell** [comment]
Can you please try to build with version 0.1.2 of this plugin?

The error implies PG build does not like the support library 4:27.1.0 however I previously changed to use that library because of some other issue.  The original change is here: https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent/commit/99d1e8b9fc39e4e77fa69c63c23debf0dc9fdbdc#diff-53f390d375398624afe1cfe1125f42bf

**Comment by darryncampbell** [comment]
One related note - you would not typically use both com-darryncampbell-enterprisebarcode AND DataWedge, they are two different ways of doing the same thing (scanning), the former using the native SDK (and hasn't been updated in a long time) and the latter using DataWedge.

**Comment by dinami-k** [comment]
thanks a lot...
you are right...
i remove com-darryncampbell-enterprisebarcode
and work my project in phonegap build....

i no test enterprisebarcode with version 0.1.2 yet, i will do that later

**Comment by dinami-k** [comment]
you can close this issue.. thanks a lot. It worked like a rock

**Comment by darryncampbell** [comment]
Brilliant.  Closing based on the above comment
