### ISSUE TITLE
Is there a way to detect if DataWedge is installed?

### ISSUE THREAD

**Issue by esskar** [darryncampbell/DataWedge-Cordova-Sample#8]
Thanks for the sample.

Do you see an easy way to detect if DataWedge is available? I am thinking about `setTimeout` before i run `registerBroadcastReceiver` and when the first intent is received, call `clearTimeout`. if no intent is received, the timeout will trigger a handler that states that DataWedge is not supported.

But is there a simpler way? (on intent level maybe)?

**Comment by darryncampbell** [comment]
That approach would be reliable but it may be simpler to use the device model or manufacturer as DataWedge is built into all Zebra Android devices.  It is conceivable that DataWedge would be disabled and you can use https://techdocs.zebra.com/datawedge/8-1/guide/api/getdatawedgestatus/ to check for this.

**Comment by esskar** [comment]
thanks. case closed.
