### ISSUE TITLE
Example app with TC8000 without response

### ISSUE THREAD

**Issue by e4r** [darryncampbell/DataWedge-Cordova-Sample#9]
Hello, I've got a TC8000 with these features:

1. DataWedge version 6.2.24
2. Scanning framework: 16.17.43.0
3. Cordova 9.0.0

I've followed the instruction, and by running the app I can see the yellow fab button that enables the device to scan barcodes, but when I scan a code, nothing happens, the DOM is not refreshed, nor any JS reference is updated.

**Comment by darryncampbell** [comment]
Did you follow the 'setup' instructions to configure your DataWedge profile?  See https://github.com/darryncampbell/DataWedge-Cordova-Sample/blob/master/README.md for more info.

**Comment by e4r** [comment]
I did

**Comment by darryncampbell** [comment]
Strange, and presumably this is running the app without modification.  Could you please export the profile and send it to me? 

`Launch DataWedge --> 3 dots --> Settings --> Export Profile --> Select Profile --> Export --> Copy the file from the device with adb pull (file name and path)`

**Comment by e4r** [comment]
Thanks for your help!
Sure, I uploaded that [on my drive](https://drive.google.com/file/d/17qy8nLRN8-DnZRvC5AFhzyPEDENmO4r9/view?usp=sharing) , it should be downloadable.

**Comment by e4r** [comment]
Another (hopefully) valuable information might be that if I don not attach the application I am working on on the profile, I can't see a fab button which enables the scanner, which is otherwise visible when I attach the application on the datawedge.

**Comment by darryncampbell** [comment]
Thank you for the profile, please make the following changes to it:
- Intent action should be `com.zebra.cordovademo.ACTION`
- Intent delivery should be `Broadcast intent`

When I changed those two things this sample worked with your profile.

**Comment by e4r** [comment]
It works! Thank you very much, but I don't understand why the intent action is called com.zebra.cordovademo.ACTION . Shouldn't that be the app's package name?

**Comment by darryncampbell** [comment]
It just needs to match whatever is defined at https://github.com/darryncampbell/DataWedge-Cordova-Sample/blob/master/www/js/index.js#L104, including the package name is just a convention but the String can be whatever you want it to be.  See https://developer.android.com/guide/topics/manifest/action-element#nm, "... it's best to use..."
